### ISSUE TITLE
Add timestamps to messages

### ISSUE THREAD

**Issue by nlohmann** [bradleyjkemp/grpc-tools#22] opened 2019-06-24 05:04 UTC
It would be great if `grpc-dump` would add timestamps of the time it records messages. This would not only allow to postprocess the output and make timing analyses, but also maybe to use the timestamps to mimic the (relative) timing behavior in `grpc-replay`.

**Comment by bradleyjkemp** [comment] 2019-06-24 12:26
Closing this as a duplicate of #9 but these are excellent use cases so I'll take this ticket as a strong vote to work on #9 at the next opportunity I get 🙂 

Do you have any strong preferences on timestamp format? By default, Go is going to marshal timestamps as RFC 3339 strings which seems standard enough that it's going to be easily parseable by most languages

**Closed by bradleyjkemp** 2019-06-24 12:26 UTC

**Comment by nlohmann** [comment] 2019-06-24 13:58
Oh, sorry no have missed that. ISO 8601 would be great, and RFC 3339 seems to be just that.
